defaults: &defaults
  working_directory: ~/markovmodel/PyEMMA
  docker:
    - image: continuumio/miniconda3

inst_conda_bld: &inst_conda_bld
  - run: conda config --add channels conda-forge
  - run: conda config --set always_yes true
  - run: conda config --set quiet true
  - run: conda install conda-build

version: 2

jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: git fetch --unshallow || true
      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install conda-build
      - run: pip install pip --upgrade;
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: python main.py
      - run: pytest -v
